# Generated by Django 3.2.16 on 2022-10-30 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigada_name', models.CharField(max_length=30, unique=True, verbose_name='Бригада')),
                ('people_amount', models.IntegerField(blank=True, null=True)),
                ('name_responsible', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ф.И.О. ответственного')),
                ('position_responsible', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность ответственного')),
                ('rank_responsible', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Разряд ответственного')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, unique=True, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=30, unique=True, verbose_name='Объект')),
                ('people_amount', models.IntegerField(blank=True, null=True)),
                ('name_responsible', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ф.И.О. ответственного')),
                ('position_responsible', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность ответственного')),
                ('rank_responsible', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Разряд ответственного')),
                ('brigada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brigadas', to='objects.brigada', verbose_name='Бригада')),
            ],
        ),
        migrations.AddField(
            model_name='brigada',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='objects.city', verbose_name='Город'),
        ),
    ]
