# Generated by Django 3.2.16 on 2022-10-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20221030_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='name_responsible',
        ),
        migrations.RemoveField(
            model_name='object',
            name='people_amount',
        ),
        migrations.RemoveField(
            model_name='object',
            name='position_responsible',
        ),
        migrations.RemoveField(
            model_name='object',
            name='rank_responsible',
        ),
    ]
