# Generated by Django 3.2.16 on 2022-10-30 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20221030_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='name_responsible',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ф.И.О. ответственного'),
        ),
        migrations.AddField(
            model_name='object',
            name='people_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='position_responsible',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность ответственного'),
        ),
        migrations.AddField(
            model_name='object',
            name='rank_responsible',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Разряд ответственного'),
        ),
    ]
