# Generated by Django 3.2.16 on 2022-10-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20221030_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='brigada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_list', to='objects.brigada', verbose_name='Бригада'),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_list', to='objects.city', verbose_name='Город'),
        ),
    ]
